[package]
name = "resonance_frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "*"
hashbrown = "0.15.2"

[dependencies.iced]
version = "0.14.0-dev"
# git = "https://github.com/iced-rs/iced.git"
git = "https://github.com/edwloef/iced.git"
branch = "fix_rectangle_snap"
no-default-features = true
features = [
	"image",
	"svg",
	"advanced",
	"fira-sans",
	"wgpu",
	"tiny-skia"
]

[dependencies.backend]
path = "../backend"
package = "resonance_backend"
