[package]
name = "resonance"
version = "0.1.0"
edition = "2021"

[dependencies]
ytdlp_bindings = "*"
directories = "*"
regex = "*"
hashbrown = { version = "0.15.2", features = ["serde"] }
colored = "*"
diesel = { version = "2.2.7", default-features = false, features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
