[package]
name = "resonance"
version = "2.0.0-dev"
edition = "2024"
authors = ["Marley <marley@marlstar.com>"]
homepage = "https://github.com/Marlstar/resonance"
repository = "https://github.com/Marlstar/resonance"
description = "A desktop music client"
keywords = ["music", "youtube", "spotify"]

[dependencies]
